In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
# grab a json file https://data.virginia.gov/resource/bre9-aqqr.json
# and load it into a pandas dataframe
df = pd.read_json('https://data.virginia.gov/resource/bre9-aqqr.json')

In [3]:
df.head()

,report_date,fips,locality,vdh_health_district,total_cases,hospitalizations,deaths
0,2023-04-18T00:00:00.000,51001,Accomack,Eastern Shore,9197,472,120
1,2023-04-18T00:00:00.000,51003,Albemarle,Blue Ridge,25612,507,209
2,2023-04-18T00:00:00.000,51005,Alleghany,Alleghany,4578,113,112
3,2023-04-18T00:00:00.000,51007,Amelia,Piedmont,3603,186,64
4,2023-04-18T00:00:00.000,51009,Amherst,Central Virginia,9728,476,114

In [19]:
# grab a couple of xls files: https://demographics.coopercenter.org/sites/demographics/files/media/files/2020-07/Census_2019_RaceEstimates_forVA_0.xls
# https://demographics.coopercenter.org/sites/demographics/files/media/files/2020-07/Census_2019_HispanicEstimates_forVA_0.xls
# and load them into pandas dataframes
df1 = pd.read_excel('https://demographics.coopercenter.org/sites/demographics/files/media/files/2020-07/Census_2019_RaceEstimates_forVA_0.xls', skiprows=8, header=None)
df1.columns = ['FIPS','Jurisdiction','Total_Pop','White_Alone_Cnt','White_Alone_Pct','AA_Alone_Cnt','AA_Alone_Pct','Asian_Alone_Cnt','Asian_Alone_Pct','Other_Alone_Cnt','Other_Alone_Pct','Two_More_Cnt','Two_More_Pct']	
df2 = pd.read_excel('https://demographics.coopercenter.org/sites/demographics/files/media/files/2020-07/Census_2019_HispanicEstimates_forVA_0.xls', skiprows=4)

In [18]:
df1.head(10)

,FIPS,Jurisdiction,Total_Pop,White_Alone_Cnt,White_Alone_Pct,AA_Alone_Cnt,AA_Alone_Pct,Asian_Alone_Cnt,Asian_Alone_Pct,Other_Alone_Cnt,Other_Alone_Pct,Two_More_Cnt,Two_More_Pct
0,1,Accomack County,32316,21899,0.677652,9304,0.287907,257,0.007953,293,0.009067,563,0.017422
1,3,Albemarle County,109330,89388,0.817598,10600,0.096954,6051,0.055346,483,0.004418,2808,0.025684
2,5,Alleghany County,14860,13783,0.927524,698,0.046972,46,0.003096,56,0.003769,277,0.018641
3,7,Amelia County,13145,10050,0.764549,2688,0.204488,80,0.006086,85,0.006466,242,0.018410
4,9,Amherst County,31605,24299,0.768834,6041,0.191141,180,0.005695,305,0.009650,780,0.024680
5,11,Appomattox County,15911,12521,0.786940,2951,0.185469,61,0.003834,56,0.003520,322,0.020238
6,13,Arlington County,236842,177639,0.750032,22922,0.096782,25945,0.109546,1840,0.007769,8496,0.035872
7,15,Augusta County,75558,70102,0.927791,3518,0.046560,490,0.006485,223,0.002951,1225,0.016213
8,17,Bath County,4147,3853,0.929105,201,0.048469,20,0.004823,9,0.002170,64,0.015433
9,19,Bedford County,78997,70750,0.895604,5697,0.072117,975,0.012342,299,0.003785,1276,0.016153

In [20]:
df2.head()

,FIPS,Jurisdiction,"Decennial Census Count, April 1, 2010",Unnamed: 3,Unnamed: 4,"Population Estimate, July 1, 2019",Unnamed: 6,Unnamed: 7,"April 1, 2010 - July 1, 2019",Unnamed: 9
0,NaN,NaN,Total Population,Hispanic Population,NaN,Total Population,Hispanic Population,NaN,Hispanic Change,NaN
1,NaN,NaN,NaN,Total Hispanic,(%),NaN,Total Hispanic,(%),Total Hispanic,(%)
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Virginia,8001024,631825,0.078968,8535519,834422,0.097759,202597,0.320654
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN